// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwhigsfdccbbsyumahzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aGlnc2ZkY2NiYnN5dW1haHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzcyNjUsImV4cCI6MjA2NDg1MzI2NX0.D7HXTGrIYUHQmhICuMXBMxvh_dSpghat7Sq5RQm-Y50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);